require("luasnip.loaders.from_vscode").lazy_load()
vim.keymap.set("n", "<Leader>rc", ":lua require('ror.commands').list_commands()<CR>", { silent = true })
vim.keymap.set("n", "<Leader>tf", ":lua require('ror.test').run()<CR>")
vim.keymap.set("n", "<Leader>tl", ":lua require('ror.test').run('Line')<CR>")
vim.keymap.set("n", "<Leader>tc", ":lua require('ror.test').clear()<CR>")
vim.keymap.set("n", "<Leader>ta", ":lua require('ror.test').attach_terminal()<CR>")
vim.keymap.set("n", "<Leader>cs", ":lua require('ror.coverage').show()<CR>")
vim.keymap.set("n", "<Leader>ch", ":lua require('ror.coverage').clear()<CR>")
